global:
  scrape_interval: 0s100ms

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: fastapi
    static_configs:
      - targets: ['192.168.1.75:8000']